# Generated by Django 4.1.3 on 2022-11-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmetherologic',
            name='status',
            field=models.CharField(choices=[('o', 'observation'), ('a', 'active'), ('e', 'expired'), ('d', 'destroyed')], default='o', max_length=1, verbose_name='status of event'),
        ),
    ]
