# Generated by Django 4.1.3 on 2022-11-15 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_eventmetherologic_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventmetherologic',
            table='event',
        ),
    ]
